version: '3'

services:
  app:
    image: docker-elkstack-APM-Logstash/demo-app:1.0.0
    build:
      context: demo-app
      dockerfile: Dockerfile
    filebeat:
      hostname: filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (RDONLY) :
      - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
      -logstash

  kibana:
    image: kibana:6.5.2
    environment:
      - "LOGGIN_QUIET=true"
    links:
      - elasticsearch
    port:
    - 5601:5601

  elasticsearch:
    hostname: elasticsearch
    image: docker-elkstack-APM-Logstash/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-elkstack-APM-Logstash-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    ports:
      - 9200:9200