version: '3'

services:
  app:
    image: docker-logstash-elk/demo-app:1.0.0
    build:
      context: demo-app
      dockerfile: Dockerfile
    filebeat:
      hostname: filebeat
      dockerfile: Dockerfile
    volumes:
      # needed to access all docker logs (RDONLY) :
      - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
      -logstash
  kibana:
    image: kibana:6.5.2
    environment:
      - "LOGGIN_QUIET=true"
    links:
      - elasticsearch
    port:
    - 5601:5601